menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags

social:
  - slug: twitter
    url: https://twitter.com/javierdearcosTL
  - slug: linkedin
    url: https://www.linkedin.com/in/javierdearcos
  - slug: github
    url: https://github.com/javierdearcos
  - slug: envelope
    url: mailto:fj.dearcos@gmail.com
  - slug: rss
    url: /atom.xml

# gitment
gitment: true
gitment_owner: javierdearcos
gitment_repo: javierdearcos.github.io
gitment_client_id: f6523fdf6e6a86882c6a
gitment_client_secret: 49ae80c1a41f44d7c07ff308997712fe76b2a513

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-167401170-1

# whether to show read more button when showing article in excerpt in main page
read_more: false
