categories: "Categorías"
tags: "Etiquetas"
prev: "Anterior"
next: "Siguiente"
comment: "Commentarios"
archive_a: "Archivo"
archive_b: "Archivo: %s"
page: "Página %d"
recent_posts: "Entradas Recientes"
read_more: "... Continuar leyendo"

Home: "Inicio"
Archives: "Archivo"
Categories: "Categorías"
Tags: "Etiquetas"
About: "Sobre mí"
Links: "Enlaces"
RSS: "RSS"